version: '3.7'
services: 
    apache-postgres:
        build: ./docker/apache-postgres
        image: apache-postgres
        container_name: apache-postgres
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
