version: '3.7'
services: 
    laravel-apache:
        build: ./docker/apache
        image: laravel-apache
        container_name: laravel-apache
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80